name: Deploy to Azure

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if artifact exists
      id: artifact-check
      run: |
        if [[ ! -f target/*.jar ]]; then
          echo "Artifact not found, running Maven build and test"
          #mvn clean test
        fi

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: superhero
        slot-name: <azure-webapp-slot-name> # Optional
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar
